[package]
authors = ["rich-murphey <rich@murphey.org>"]
name = "sqlx-actix-test"
version = "0.1.0"
edition = "2018"

[dependencies]
actix-web = "3.3.2"
anyhow = "1.0.38"
dotenv = "0.15.0"
env_logger = "0.8.2"
futures = "0.3.12"
log = "0.4.14"
num_cpus = "1.13.0"
serde = { version = "1.0.123", features = ["derive"] }
serde_json = { version = "1.0.61", features = ["raw_value"] }
sqlx = { version = "0.4.2", features = [ "postgres", "runtime-actix-rustls" ] }
sqlx-actix-streaming = { path = "..", features = ["macros"] }
sys-info = "0.8.0"
thiserror = "1.0.23"
