[package]
authors = ["rich-murphey <rich@murphey.org>"]
name = "sqlx-actix-test"
version = "0.1.0"
edition = "2018"
publish = false

[dependencies]
actix-http = "3.0.0-beta.1"
actix-web = "4.0.0-beta.1"
anyhow = "1.0.38"
dotenv = "0.15.0"
env_logger = "0.8.2"
futures = "0.3.12"
log = "0.4.13"
num_cpus = "1.13.0"
serde = { version = "1.0.120", features = ["derive"] }
serde_json = { version = "1.0.61", features = ["raw_value"] }
sqlx = { git = "https://github.com/launchbadge/sqlx", features = [ "postgres", "runtime-actix-rustls", "json", "chrono" ]}
sys-info = "0.7.0"
thiserror = "1.0.23"
sqlx-actix-streaming = { path = "..", features = ["macros"] }
