[package]
name = "sqlx-actix-streaming"
version = "0.1.0"
authors = ["rich-murphey <rich@murphey.org>"]
edition = "2018"
publish = false
license = "MIT OR Apache-2.0"
readme = "README.md"

[features]
default = []
macros = []

[dependencies]
futures = "0"
ouroboros = "0"
serde = "1"
serde_json = "1"
actix-web = "4.0.0-beta.1"
sqlx = { git = "https://github.com/lumeohq/sqlx", branch = "tokio-1.0", features = [ "postgres", "json", "chrono", "runtime-actix-rustls" ]}
