[package]
name = "sqlx-actix-streaming"
version = "0.1.0"
authors = ["rich-murphey <rich@murphey.org>"]
edition = "2018"
publish = false
license = "MIT OR Apache-2.0"
readme = "README.md"

[features]
default = []
macros = []
logging = ["log"]

runtime-actix-native-tls = [ "sqlx/runtime-actix-native-tls" ]
runtime-actix-rustls = [ "sqlx/runtime-actix-rustls" ]
runtime-async-std-native-tls = [ "sqlx/runtime-async-std-native-tls" ]
runtime-async-std-rustls = [ "sqlx/runtime-async-std-rustls" ]
runtime-tokio-native-tls = [ "sqlx/runtime-tokio-native-tls" ]
runtime-tokio-rustls = [ "sqlx/runtime-tokio-rustls" ]

[dependencies]
actix-web = "3"
futures = "0"
log = { version = "0", optional = true }
ouroboros = "0"
serde = "1"
serde_json = "1"
sqlx = "0.4"
typed-builder = "0"
