[package]
name = "sqlx-actix-streaming"
version = "0.1.0"
authors = ["rich-murphey <rich@murphey.org>"]
edition = "2018"
publish = false
license = "MIT OR Apache-2.0"
readme = "README.md"

[features]
default = [ "sqlx/postgres", "sqlx/runtime-actix-rustls" ]
macros = []
logging = ["log"]

[dependencies]
actix-web = "3"
futures = "0"
log = { version = "0", optional = true }
ouroboros = "0"
serde = "1"
serde_json = "1"
sqlx = "0"
