[package]
name = "sqlx-actix-streaming"
version = "0.1.0"
authors = ["rich-murphey <rich@murphey.org>"]
edition = "2018"
publish = false
license = "MIT OR Apache-2.0"
readme = "README.md"

[features]
default = []
macros = []

[dependencies]
actix-web = "3.3.2"
bytes = "1.0.1"
futures = "0.3.12"
ouroboros = "0.8.0"
serde = "1.0.123"
serde_json = "1.0.61"
sqlx = "0.4.2"
