[package]
name = "sqlx-actix-streaming"
version = "0.1.0"
authors = ["rich-murphey <rich@murphey.org>"]
edition = "2018"
publish = false
license = "MIT OR Apache-2.0"
# readme = "README.md"

[features]
default = ["runtime-tokio-rustls"]

runtime-actix-native-tls = ["sqlx/runtime-actix-native-tls"]
runtime-async-std-native-tls = ["sqlx/runtime-async-std-native-tls"]
runtime-tokio-native-tls = ["sqlx/runtime-tokio-native-tls"]
runtime-actix-rustls = ["sqlx/runtime-actix-rustls"]
runtime-async-std-rustls = ["sqlx/runtime-async-std-rustls"]
runtime-tokio-rustls = ["sqlx/runtime-tokio-rustls"]

macros = []
docs = ["rustls", "postgres"]
test = ["rustls", "postgres"]

# database
any = ["sqlx/any"]
postgres = ["sqlx/postgres"]

# tls implementation
rustls = ["sqlx/runtime-tokio-rustls"]

[dependencies]
futures = "0.3.12"
ouroboros = "0.8.0"
serde = "1.0.120"
serde_json = "1.0.61"

# actix-web = "4.0.0-beta.1"
# sqlx = { git = "https://github.com/launchbadge/sqlx" }
# bytes = "1.0.1"

actix-web = "3.3.2"
bytes = "0.5.6"
sqlx = "0.4.2"

